# Generated by Django 2.0.4 on 2018-04-22 02:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images/%Y/%m/%D/')),
                ('img_description', models.CharField(max_length=100)),
                ('added_on', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
