# Generated by Django 2.0.4 on 2018-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimages',
            name='img_description',
            field=models.TextField(max_length=100),
        ),
    ]
