# Generated by Django 2.0.4 on 2018-04-27 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20180426_0839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadimages',
            old_name='img_description',
            new_name='description',
        ),
    ]
